defaults:
  - base_synchronous_mt_strategy
  - population: simple_population
  - genome_factory: toy
  - fitness: toy_mae
  - dataset: base_toy_dataset

output_directory: "output/test"
nsteps: 32000
  
