name: Sphinx build

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ 3.8 ] # is 3.8 required here...?

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Install dependencies
                run: |
                    sudo apt-get install -y exempi
                    pip install -e .
                    pip install -r requirements-cpu.txt
                    pip install -r requirements-dev.txt
                    pip install -r requirements-uniti.txt
            -   name: Sphinx build HTML
                run: |
                    sphinx-build -b html docs/source docs/build/html
            -   name: Deploy
                uses: Airtonomy/actions-gh-pages@v3.8.0
                if: github.ref == 'refs/heads/main'
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: docs/build/html
